package main

var AllSongsIDs = []string{
	"100Bills",
	"BalearicPumping",
	"BeatSaber",
	"Breezer",
	"CommercialPumping",
	"CountryRounds",
	"Escape",
	"Legend",
	"LvlInsane",
	"TurnMeOn",
	"BeThereForYou",
	"Elixia",
	"INeedYou",
	"RumNBass",
	"UnlimitedPower",
	"Origins",
	"ReasonForLiving",
	"FullCharge",
	"GiveALittleLove",
	"Immortal",
	"BurningSands",
	"FitBeat",
	"CrabRave",
	"PopStars",
	"OneHope",
	"AngelVoices",
	"ExitThisEarthsAtomosphere",
	"Ghost",
	"LightItUp",
	"Crystallized",
	"CycleHit",
	"WhatTheCat",
}
